[package]
name = "traffic_light_ui"
version = "0.1.0"
edition = "2021"

#[dependencies]
#eframe = "0.16.0"  # Check for the latest version on crates.io

[dependencies]
egui = "0.27.0"
eframe = "0.27.0"

[workspace]
members = ["."]
